"use client"

import { useState, useEffect, useCallback } from "react"
import { Button } from "@/components/ui/button"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { ArrowLeft } from "lucide-react"
import { useRouter } from "next/navigation"
import RecordedStreamsLibrary from "@/components/grocery/live-shopping/recorded-streams-library"
import { toast } from "@/components/ui/use-toast"
import { RecordingService } from "@/lib/recording-service"
import type { RecordedStream, StreamHighlight } from "@/types/recording"
import type { StreamRecording } from "@/types/live-shopping"

const toLiveShoppingRecording = (recording: RecordedStream): StreamRecording => ({
  id: recording.id,
  streamId: recording.id,
  title: recording.title,
  description: recording.description,
  thumbnailUrl: recording.thumbnailUrl,
  recordingUrl: recording.recordingUrl,
  duration: recording.duration,
  fileSize: recording.fileSize,
  startTime: recording.createdAt,
  endTime: undefined,
  isProcessing: recording.isProcessing,
  isPublic: recording.isPublic,
  viewCount: recording.viewCount,
  downloadCount: recording.downloadCount,
  highlights:
    recording.highlights?.map((highlight: StreamHighlight) => ({
      ...highlight,
      createdBy: "host",
      isAutoGenerated: false,
    })) || [],
  chapters: recording.chapters || [],
  quality: recording.quality || "high",
  format: "mp4",
})

export default function RecordingsPage() {
  const router = useRouter()
  const [recordings, setRecordings] = useState<StreamRecording[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  const loadRecordings = useCallback(async () => {
    try {
      setLoading(true)
      setError(null)
      const recordingData = await RecordingService.getRecordings()
      setRecordings(recordingData.map(toLiveShoppingRecording))
    } catch (err) {
      const message = err instanceof Error ? err.message : "Failed to load recordings"
      setError(message)
      toast({
        title: "Unable to load recordings",
        description: message,
      })
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => {
    void loadRecordings()
  }, [loadRecordings])

  const handlePlayRecording = (recording: StreamRecording) => {
    if (!recording.recordingUrl) {
      toast({ title: "Recording unavailable", description: "No playback URL is currently available." })
      return
    }

    window.open(recording.recordingUrl, "_blank", "noopener,noreferrer")
  }

  const handleDownloadRecording = async (recording: StreamRecording) => {
    try {
      await RecordingService.downloadRecording(recording.id)
      toast({
        title: "Download Started",
        description: `Downloading "${recording.title}"...`,
      })
    } catch (err) {
      const message = err instanceof Error ? err.message : "Failed to start download"
      toast({
        title: "Download failed",
        description: message,
        action: (
          <Button variant="outline" size="sm" onClick={() => handleDownloadRecording(recording)}>
            Retry
          </Button>
        ),
      })
    }
  }

  const handleShareRecording = async (recording: StreamRecording) => {
    try {
      const shareUrl = await RecordingService.shareRecording(recording.id)
      await navigator.clipboard.writeText(shareUrl)
      toast({
        title: "Link Copied",
        description: "Recording link copied to clipboard",
      })
      await loadRecordings()
    } catch (err) {
      const message = err instanceof Error ? err.message : "Failed to share recording"
      toast({
        title: "Share failed",
        description: message,
        action: (
          <Button variant="outline" size="sm" onClick={() => handleShareRecording(recording)}>
            Retry
          </Button>
        ),
      })
    }
  }

  const handleCreateClip = async (recording: StreamRecording) => {
    try {
      await RecordingService.createClip(recording.id, {
        id: crypto.randomUUID(),
        title: `${recording.title} Highlight`,
        startTime: 0,
        endTime: Math.min(recording.duration, 30),
        viewCount: 0,
      })
      toast({
        title: "Clip Created",
        description: "A new clip was created from the recording.",
      })
      await loadRecordings()
    } catch (err) {
      const message = err instanceof Error ? err.message : "Failed to create clip"
      toast({
        title: "Clip creation failed",
        description: message,
        action: (
          <Button variant="outline" size="sm" onClick={() => handleCreateClip(recording)}>
            Retry
          </Button>
        ),
      })
    }
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-gradient-to-b from-white to-orange-50 dark:from-gray-950 dark:to-gray-900">
        <div className="container mx-auto py-8">
          <div className="animate-pulse space-y-4">
            <div className="h-8 bg-gray-200 rounded w-1/4"></div>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              {[...Array(6)].map((_, i) => (
                <div key={i} className="bg-gray-200 rounded-lg h-64"></div>
              ))}
            </div>
          </div>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-gradient-to-b from-white to-orange-50 dark:from-gray-950 dark:to-gray-900">
      <div className="container mx-auto py-8">
        {error ? (
          <Card className="mb-4 border-red-300">
            <CardHeader>
              <CardTitle className="text-sm font-medium">Could not refresh recordings</CardTitle>
            </CardHeader>
            <CardContent className="flex items-center justify-between gap-4">
              <span className="text-sm text-muted-foreground">{error}</span>
              <Button size="sm" onClick={loadRecordings}>
                Retry
              </Button>
            </CardContent>
          </Card>
        ) : null}

        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center gap-4">
            <Button
              variant="ghost"
              size="icon"
              onClick={() => router.back()}
              className="hover:bg-orange-100 dark:hover:bg-orange-900/20"
            >
              <ArrowLeft className="h-5 w-5" />
            </Button>
            <div>
              <h1 className="text-3xl font-bold bg-gradient-to-r from-orange-500 to-amber-400 bg-clip-text text-transparent">
                Stream Recordings
              </h1>
              <p className="text-muted-foreground">Watch and manage your recorded live shopping streams</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <Button
              variant="outline"
              onClick={() => router.push("/grocery/live")}
              className="border-orange-200 dark:border-orange-800"
            >
              Back to Live
            </Button>
          </div>
        </div>

        <Tabs defaultValue="all" className="space-y-4">
          <TabsList>
            <TabsTrigger value="all">All Recordings</TabsTrigger>
            <TabsTrigger value="public">Public</TabsTrigger>
            <TabsTrigger value="private">Private</TabsTrigger>
            <TabsTrigger value="processing">Processing</TabsTrigger>
          </TabsList>

          <TabsContent value="all" className="mt-0">
            <RecordedStreamsLibrary
              recordings={recordings}
              onPlay={handlePlayRecording}
              onDownload={handleDownloadRecording}
              onShare={handleShareRecording}
              onCreateClip={handleCreateClip}
            />
          </TabsContent>

          <TabsContent value="public" className="mt-0">
            <RecordedStreamsLibrary
              recordings={recordings.filter((r) => r.isPublic)}
              onPlay={handlePlayRecording}
              onDownload={handleDownloadRecording}
              onShare={handleShareRecording}
              onCreateClip={handleCreateClip}
            />
          </TabsContent>

          <TabsContent value="private" className="mt-0">
            <RecordedStreamsLibrary
              recordings={recordings.filter((r) => !r.isPublic)}
              onPlay={handlePlayRecording}
              onDownload={handleDownloadRecording}
              onShare={handleShareRecording}
              onCreateClip={handleCreateClip}
            />
          </TabsContent>

          <TabsContent value="processing" className="mt-0">
            <RecordedStreamsLibrary
              recordings={recordings.filter((r) => r.isProcessing)}
              onPlay={handlePlayRecording}
              onDownload={handleDownloadRecording}
              onShare={handleShareRecording}
              onCreateClip={handleCreateClip}
            />
          </TabsContent>
        </Tabs>

        <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mt-8">
          <Card>
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-medium">Total Recordings</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">{recordings.length}</div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-medium">Total Views</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">{recordings.reduce((sum, r) => sum + r.viewCount, 0)}</div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-medium">Total Downloads</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">{recordings.reduce((sum, r) => sum + r.downloadCount, 0)}</div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-medium">Processing</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">{recordings.filter((r) => r.isProcessing).length}</div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}
