// Product data types
export interface ProductVariant {
  name: string
  price: number
  inStock: boolean
}

export interface ProductColor {
  name: string
  value: string
  inStock: boolean
}

export interface ProductSpecifications {
  [key: string]: string
}

export interface Product {
  id: string
  name: string
  description: string
  price: number
  originalPrice: number
  discount: number
  rating: number
  reviewCount: number
  stock: number
  sku: string
  features: string[]
  specifications: ProductSpecifications
  images: string[]
  colors: ProductColor[]
  variants: ProductVariant[]
  category: string
  brand: string
  tags: string[]
  isOrganic?: boolean
  certifications?: string[]
  origin?: string
  shelfLife?: string
}

// Mock organic product data with Indian pricing
const products: Product[] = [
  {
    id: "organic-turmeric-powder",
    name: "Premium Organic Turmeric Powder",
    description:
      "Pure, organic turmeric powder sourced directly from certified organic farms in Kerala. Rich in curcumin with anti-inflammatory properties. Perfect for cooking, health drinks, and traditional remedies.",
    price: 299,
    originalPrice: 399,
    discount: 25,
    rating: 4.8,
    reviewCount: 1247,
    stock: 45,
    sku: "ORG-TUR-500G",
    features: [
      "100% Certified Organic",
      "High Curcumin Content (3.5%)",
      "No Artificial Colors or Additives",
      "Freshly Ground from Premium Rhizomes",
      "FSSAI Certified",
      "Vacuum Packed for Freshness",
    ],
    specifications: {
      weight: "500g",
      origin: "Kerala, India",
      shelfLife: "24 months",
      certification: "India Organic, USDA Organic",
      curcuminContent: "3.5%",
      packaging: "Food Grade Aluminum Pouch",
    },
    images: [
      "/placeholder.svg?height=600&width=600&text=Organic+Turmeric+Powder",
      "/placeholder.svg?height=600&width=600&text=Turmeric+Farm+Kerala",
      "/placeholder.svg?height=600&width=600&text=Turmeric+Certification",
      "/placeholder.svg?height=600&width=600&text=Turmeric+Packaging",
    ],
    colors: [{ name: "Golden Yellow", value: "#FFD700", inStock: true }],
    variants: [
      { name: "500g Pouch", price: 299, inStock: true },
      { name: "1kg Pouch", price: 549, inStock: true },
      { name: "250g Trial Pack", price: 159, inStock: true },
    ],
    category: "Spices & Herbs",
    brand: "OrganicIndia",
    tags: ["Organic", "Turmeric", "Spices", "Health", "Ayurveda"],
    isOrganic: true,
    certifications: ["India Organic", "USDA Organic", "FSSAI"],
    origin: "Kerala, India",
    shelfLife: "24 months",
  },
  {
    id: "organic-basmati-rice",
    name: "Himalayan Organic Basmati Rice",
    description:
      "Premium aged organic basmati rice from the foothills of Himalayas. Naturally aromatic with extra-long grains. Aged for 2 years for enhanced flavor and texture.",
    price: 449,
    originalPrice: 599,
    discount: 25,
    rating: 4.7,
    reviewCount: 892,
    stock: 32,
    sku: "ORG-BAS-1KG",
    features: [
      "100% Organic Basmati",
      "2 Years Naturally Aged",
      "Extra Long Grain (8.2mm)",
      "Low Glycemic Index",
      "No Pesticides or Chemicals",
      "Traditional Farming Methods",
    ],
    specifications: {
      weight: "1kg",
      origin: "Uttarakhand, India",
      shelfLife: "12 months",
      certification: "India Organic, NPOP",
      grainLength: "8.2mm",
      aging: "2 years",
    },
    images: [
      "/placeholder.svg?height=600&width=600&text=Organic+Basmati+Rice",
      "/placeholder.svg?height=600&width=600&text=Himalayan+Rice+Fields",
      "/placeholder.svg?height=600&width=600&text=Rice+Grains+Close+Up",
      "/placeholder.svg?height=600&width=600&text=Cooked+Basmati+Rice",
    ],
    colors: [{ name: "Pearl White", value: "#F8F8FF", inStock: true }],
    variants: [
      { name: "1kg Pack", price: 449, inStock: true },
      { name: "5kg Pack", price: 2099, inStock: true },
      { name: "500g Trial Pack", price: 249, inStock: true },
    ],
    category: "Grains & Cereals",
    brand: "HimalayanHarvest",
    tags: ["Organic", "Basmati", "Rice", "Grains", "Premium"],
    isOrganic: true,
    certifications: ["India Organic", "NPOP"],
    origin: "Uttarakhand, India",
    shelfLife: "12 months",
  },
  {
    id: "organic-honey-raw",
    name: "Raw Organic Wildflower Honey",
    description:
      "Pure, unprocessed organic honey harvested from wildflower meadows. Rich in enzymes, antioxidants, and natural minerals. No heating or filtering preserves all natural goodness.",
    price: 649,
    originalPrice: 799,
    discount: 19,
    rating: 4.9,
    reviewCount: 1567,
    stock: 28,
    sku: "ORG-HON-500G",
    features: [
      "100% Raw & Unprocessed",
      "Certified Organic Wildflower",
      "Rich in Natural Enzymes",
      "No Added Sugar or Preservatives",
      "Sustainably Harvested",
      "Glass Jar Packaging",
    ],
    specifications: {
      weight: "500g",
      origin: "Himachal Pradesh, India",
      shelfLife: "24 months",
      certification: "India Organic, NOP",
      moisture: "18% max",
      packaging: "Food Grade Glass Jar",
    },
    images: [
      "/placeholder.svg?height=600&width=600&text=Raw+Organic+Honey",
      "/placeholder.svg?height=600&width=600&text=Wildflower+Meadow",
      "/placeholder.svg?height=600&width=600&text=Honey+Dripping",
      "/placeholder.svg?height=600&width=600&text=Glass+Jar+Honey",
    ],
    colors: [{ name: "Golden Amber", value: "#FFBF00", inStock: true }],
    variants: [
      { name: "500g Glass Jar", price: 649, inStock: true },
      { name: "1kg Glass Jar", price: 1199, inStock: true },
      { name: "250g Trial Jar", price: 349, inStock: true },
    ],
    category: "Natural Sweeteners",
    brand: "PureNectar",
    tags: ["Organic", "Honey", "Raw", "Natural", "Wildflower"],
    isOrganic: true,
    certifications: ["India Organic", "NOP"],
    origin: "Himachal Pradesh, India",
    shelfLife: "24 months",
  },
  {
    id: "organic-green-tea",
    name: "Himalayan Organic Green Tea",
    description:
      "Premium organic green tea leaves from high-altitude gardens in Darjeeling. Hand-picked and naturally processed for maximum antioxidants and delicate flavor.",
    price: 399,
    originalPrice: 499,
    discount: 20,
    rating: 4.6,
    reviewCount: 743,
    stock: 67,
    sku: "ORG-GT-100G",
    features: [
      "High Altitude Grown (6000ft+)",
      "Hand Picked Tea Leaves",
      "Rich in Antioxidants (EGCG)",
      "No Artificial Flavors",
      "Vacuum Sealed Freshness",
      "Fair Trade Certified",
    ],
    specifications: {
      weight: "100g (50 tea bags)",
      origin: "Darjeeling, India",
      shelfLife: "24 months",
      certification: "India Organic, Fair Trade",
      caffeine: "25-30mg per cup",
      packaging: "Biodegradable Tea Bags",
    },
    images: [
      "/placeholder.svg?height=600&width=600&text=Organic+Green+Tea",
      "/placeholder.svg?height=600&width=600&text=Darjeeling+Tea+Garden",
      "/placeholder.svg?height=600&width=600&text=Tea+Leaves+Close+Up",
      "/placeholder.svg?height=600&width=600&text=Brewed+Green+Tea",
    ],
    colors: [{ name: "Fresh Green", value: "#90EE90", inStock: true }],
    variants: [
      { name: "50 Tea Bags", price: 399, inStock: true },
      { name: "100 Tea Bags", price: 749, inStock: true },
      { name: "Loose Leaf 100g", price: 449, inStock: true },
    ],
    category: "Beverages",
    brand: "TeaValley",
    tags: ["Organic", "Green Tea", "Antioxidants", "Darjeeling", "Premium"],
    isOrganic: true,
    certifications: ["India Organic", "Fair Trade"],
    origin: "Darjeeling, India",
    shelfLife: "24 months",
  },
  {
    id: "organic-coconut-oil",
    name: "Cold-Pressed Organic Coconut Oil",
    description:
      "Virgin coconut oil extracted using traditional cold-pressing methods. Rich in MCTs and lauric acid. Perfect for cooking, skincare, and hair care.",
    price: 549,
    originalPrice: 699,
    discount: 21,
    rating: 4.8,
    reviewCount: 1123,
    stock: 41,
    sku: "ORG-COC-500ML",
    features: [
      "100% Virgin Coconut Oil",
      "Cold-Pressed Extraction",
      "Rich in MCT & Lauric Acid",
      "Multi-Purpose Use",
      "No Chemicals or Bleaching",
      "Glass Bottle Packaging",
    ],
    specifications: {
      volume: "500ml",
      origin: "Kerala, India",
      shelfLife: "24 months",
      certification: "India Organic, USDA Organic",
      extraction: "Cold-Pressed",
      packaging: "Dark Glass Bottle",
    },
    images: [
      "/placeholder.svg?height=600&width=600&text=Organic+Coconut+Oil",
      "/placeholder.svg?height=600&width=600&text=Coconut+Plantation",
      "/placeholder.svg?height=600&width=600&text=Cold+Press+Process",
      "/placeholder.svg?height=600&width=600&text=Glass+Bottle+Oil",
    ],
    colors: [{ name: "Clear White", value: "#FFFEF7", inStock: true }],
    variants: [
      { name: "500ml Glass Bottle", price: 549, inStock: true },
      { name: "1L Glass Bottle", price: 999, inStock: true },
      { name: "250ml Trial Bottle", price: 299, inStock: true },
    ],
    category: "Oils & Ghee",
    brand: "CoconutPure",
    tags: ["Organic", "Coconut Oil", "Virgin", "Cold-Pressed", "MCT"],
    isOrganic: true,
    certifications: ["India Organic", "USDA Organic"],
    origin: "Kerala, India",
    shelfLife: "24 months",
  },
  {
    id: "organic-quinoa",
    name: "Bolivian Organic White Quinoa",
    description:
      "Premium organic quinoa imported from Bolivia. Complete protein source with all 9 essential amino acids. Gluten-free superfood perfect for healthy meals.",
    price: 799,
    originalPrice: 999,
    discount: 20,
    rating: 4.7,
    reviewCount: 456,
    stock: 23,
    sku: "ORG-QUI-500G",
    features: [
      "Complete Protein Source",
      "All 9 Essential Amino Acids",
      "Gluten-Free Superfood",
      "High in Fiber & Iron",
      "Pre-Washed & Ready to Cook",
      "Imported from Bolivia",
    ],
    specifications: {
      weight: "500g",
      origin: "Bolivia",
      shelfLife: "18 months",
      certification: "USDA Organic, Fair Trade",
      protein: "14g per 100g",
      packaging: "Resealable Pouch",
    },
    images: [
      "/placeholder.svg?height=600&width=600&text=Organic+White+Quinoa",
      "/placeholder.svg?height=600&width=600&text=Bolivian+Quinoa+Fields",
      "/placeholder.svg?height=600&width=600&text=Quinoa+Grains+Close+Up",
      "/placeholder.svg?height=600&width=600&text=Cooked+Quinoa+Bowl",
    ],
    colors: [{ name: "Ivory White", value: "#FFFFF0", inStock: true }],
    variants: [
      { name: "500g Pouch", price: 799, inStock: true },
      { name: "1kg Pouch", price: 1499, inStock: true },
      { name: "250g Trial Pack", price: 429, inStock: false },
    ],
    category: "Grains & Cereals",
    brand: "SuperGrains",
    tags: ["Organic", "Quinoa", "Protein", "Gluten-Free", "Superfood"],
    isOrganic: true,
    certifications: ["USDA Organic", "Fair Trade"],
    origin: "Bolivia",
    shelfLife: "18 months",
  },
  {
    id: "organic-amla-powder",
    name: "Pure Organic Amla Powder",
    description:
      "Fresh amla powder rich in Vitamin C and antioxidants. Sourced from organic farms in Rajasthan. Perfect for immunity boosting and hair care.",
    price: 249,
    originalPrice: 329,
    discount: 24,
    rating: 4.7,
    reviewCount: 892,
    stock: 56,
    sku: "ORG-AML-250G",
    features: [
      "100% Pure Amla Powder",
      "Rich in Vitamin C",
      "Natural Immunity Booster",
      "Hair & Skin Benefits",
      "No Artificial Additives",
      "Sun-Dried Process",
    ],
    specifications: {
      weight: "250g",
      origin: "Rajasthan, India",
      shelfLife: "18 months",
      certification: "India Organic, FSSAI",
      vitaminC: "600mg per 100g",
      packaging: "Food Grade Pouch",
    },
    images: [
      "/placeholder.svg?height=600&width=600&text=Organic+Amla+Powder",
      "/placeholder.svg?height=600&width=600&text=Fresh+Amla+Fruits",
      "/placeholder.svg?height=600&width=600&text=Amla+Tree+Farm",
      "/placeholder.svg?height=600&width=600&text=Amla+Powder+Close+Up",
    ],
    colors: [{ name: "Natural Green", value: "#90EE90", inStock: true }],
    variants: [
      { name: "250g Pouch", price: 249, inStock: true },
      { name: "500g Pouch", price: 449, inStock: true },
      { name: "100g Trial Pack", price: 129, inStock: true },
    ],
    category: "Superfoods",
    brand: "AyurVeda Organics",
    tags: ["Organic", "Amla", "Vitamin C", "Immunity", "Ayurveda"],
    isOrganic: true,
    certifications: ["India Organic", "FSSAI"],
    origin: "Rajasthan, India",
    shelfLife: "18 months",
  },
  {
    id: "organic-finger-millet",
    name: "Organic Finger Millet (Ragi)",
    description:
      "Nutritious finger millet grown organically in Karnataka. High in calcium, iron, and fiber. Perfect for making healthy porridge, rotis, and baked goods.",
    price: 189,
    originalPrice: 249,
    discount: 24,
    rating: 4.6,
    reviewCount: 567,
    stock: 78,
    sku: "ORG-RAG-1KG",
    features: [
      "High in Calcium & Iron",
      "Gluten-Free Grain",
      "Rich in Amino Acids",
      "Low Glycemic Index",
      "Traditional Superfood",
      "Naturally Grown",
    ],
    specifications: {
      weight: "1kg",
      origin: "Karnataka, India",
      shelfLife: "12 months",
      certification: "India Organic, NPOP",
      calcium: "344mg per 100g",
      packaging: "Vacuum Sealed Pouch",
    },
    images: [
      "/placeholder.svg?height=600&width=600&text=Organic+Finger+Millet",
      "/placeholder.svg?height=600&width=600&text=Ragi+Fields+Karnataka",
      "/placeholder.svg?height=600&width=600&text=Millet+Grains+Close+Up",
      "/placeholder.svg?height=600&width=600&text=Ragi+Flour+Bowl",
    ],
    colors: [{ name: "Reddish Brown", value: "#8B4513", inStock: true }],
    variants: [
      { name: "1kg Whole Grain", price: 189, inStock: true },
      { name: "500g Flour", price: 129, inStock: true },
      { name: "2kg Family Pack", price: 349, inStock: true },
    ],
    category: "Millets",
    brand: "MilletMagic",
    tags: ["Organic", "Millet", "Ragi", "Calcium", "Gluten-Free"],
    isOrganic: true,
    certifications: ["India Organic", "NPOP"],
    origin: "Karnataka, India",
    shelfLife: "12 months",
  },
  {
    id: "organic-neem-oil",
    name: "Cold-Pressed Organic Neem Oil",
    description:
      "Pure neem oil extracted through cold-pressing method. Natural pesticide and skincare solution. Perfect for organic gardening and personal care.",
    price: 399,
    originalPrice: 499,
    discount: 20,
    rating: 4.5,
    reviewCount: 423,
    stock: 34,
    sku: "ORG-NEE-250ML",
    features: [
      "100% Pure Neem Oil",
      "Cold-Pressed Extraction",
      "Natural Pesticide",
      "Skincare Benefits",
      "Organic Gardening",
      "Multi-Purpose Use",
    ],
    specifications: {
      volume: "250ml",
      origin: "Andhra Pradesh, India",
      shelfLife: "24 months",
      certification: "India Organic, USDA Organic",
      extraction: "Cold-Pressed",
      packaging: "Dark Glass Bottle",
    },
    images: [
      "/placeholder.svg?height=600&width=600&text=Organic+Neem+Oil",
      "/placeholder.svg?height=600&width=600&text=Neem+Tree+Farm",
      "/placeholder.svg?height=600&width=600&text=Neem+Seeds",
      "/placeholder.svg?height=600&width=600&text=Neem+Oil+Bottle",
    ],
    colors: [{ name: "Golden Yellow", value: "#DAA520", inStock: true }],
    variants: [
      { name: "250ml Bottle", price: 399, inStock: true },
      { name: "500ml Bottle", price: 749, inStock: true },
      { name: "100ml Trial Size", price: 199, inStock: true },
    ],
    category: "Personal Care",
    brand: "NeemNature",
    tags: ["Organic", "Neem", "Skincare", "Natural", "Ayurveda"],
    isOrganic: true,
    certifications: ["India Organic", "USDA Organic"],
    origin: "Andhra Pradesh, India",
    shelfLife: "24 months",
  },
  {
    id: "organic-jaggery-powder",
    name: "Organic Sugarcane Jaggery Powder",
    description:
      "Traditional jaggery powder made from organic sugarcane. Rich in iron and minerals. Natural sweetener perfect for desserts and beverages.",
    price: 179,
    originalPrice: 229,
    discount: 22,
    rating: 4.8,
    reviewCount: 1034,
    stock: 89,
    sku: "ORG-JAG-500G",
    features: [
      "100% Organic Sugarcane",
      "Rich in Iron & Minerals",
      "Traditional Processing",
      "No Chemical Additives",
      "Natural Sweetener",
      "Unrefined Sugar Alternative",
    ],
    specifications: {
      weight: "500g",
      origin: "Maharashtra, India",
      shelfLife: "18 months",
      certification: "India Organic, FSSAI",
      iron: "11mg per 100g",
      packaging: "Moisture-Proof Pouch",
    },
    images: [
      "/placeholder.svg?height=600&width=600&text=Organic+Jaggery+Powder",
      "/placeholder.svg?height=600&width=600&text=Sugarcane+Fields",
      "/placeholder.svg?height=600&width=600&text=Jaggery+Making+Process",
      "/placeholder.svg?height=600&width=600&text=Jaggery+Powder+Bowl",
    ],
    colors: [{ name: "Golden Brown", value: "#CD853F", inStock: true }],
    variants: [
      { name: "500g Powder", price: 179, inStock: true },
      { name: "1kg Powder", price: 329, inStock: true },
      { name: "500g Blocks", price: 169, inStock: true },
    ],
    category: "Jaggery & Gur",
    brand: "SweetTradition",
    tags: ["Organic", "Jaggery", "Natural Sweetener", "Iron Rich", "Traditional"],
    isOrganic: true,
    certifications: ["India Organic", "FSSAI"],
    origin: "Maharashtra, India",
    shelfLife: "18 months",
  },
  {
    id: "organic-moringa-powder",
    name: "Premium Organic Moringa Leaf Powder",
    description:
      "Nutrient-dense moringa leaf powder from organic farms. Known as the 'miracle tree', rich in vitamins, minerals, and antioxidants.",
    price: 349,
    originalPrice: 449,
    discount: 22,
    rating: 4.7,
    reviewCount: 678,
    stock: 42,
    sku: "ORG-MOR-200G",
    features: [
      "100% Pure Moringa Leaves",
      "92 Nutrients & Vitamins",
      "High Protein Content",
      "Natural Energy Booster",
      "Antioxidant Rich",
      "Shade Dried Process",
    ],
    specifications: {
      weight: "200g",
      origin: "Tamil Nadu, India",
      shelfLife: "24 months",
      certification: "India Organic, USDA Organic",
      protein: "27g per 100g",
      packaging: "UV Protected Jar",
    },
    images: [
      "/placeholder.svg?height=600&width=600&text=Organic+Moringa+Powder",
      "/placeholder.svg?height=600&width=600&text=Moringa+Tree+Leaves",
      "/placeholder.svg?height=600&width=600&text=Moringa+Farm+Tamil+Nadu",
      "/placeholder.svg?height=600&width=600&text=Moringa+Powder+Jar",
    ],
    colors: [{ name: "Vibrant Green", value: "#32CD32", inStock: true }],
    variants: [
      { name: "200g Jar", price: 349, inStock: true },
      { name: "400g Jar", price: 649, inStock: true },
      { name: "100g Trial Jar", price: 199, inStock: true },
    ],
    category: "Superfoods",
    brand: "MoringaMagic",
    tags: ["Organic", "Moringa", "Superfood", "Protein", "Vitamins"],
    isOrganic: true,
    certifications: ["India Organic", "USDA Organic"],
    origin: "Tamil Nadu, India",
    shelfLife: "24 months",
  },
  {
    id: "organic-black-rice",
    name: "Organic Black Rice (Forbidden Rice)",
    description:
      "Antioxidant-rich black rice from Manipur. Known as 'forbidden rice', this ancient grain is packed with anthocyanins and nutrients.",
    price: 599,
    originalPrice: 749,
    discount: 20,
    rating: 4.6,
    reviewCount: 234,
    stock: 18,
    sku: "ORG-BLK-1KG",
    features: [
      "Ancient Heirloom Variety",
      "Rich in Anthocyanins",
      "High Antioxidant Content",
      "Naturally Purple Color",
      "Gluten-Free Grain",
    
