import { WorkflowNodeDefinition } from "@/types/workflow-kit"

export const WORKFLOW_NODE_DEFINITIONS: WorkflowNodeDefinition[] = [
  {
    type: "payment.webhook_event_trigger",
    label: "Payment Event Trigger",
    description: "Start workflow from payment lifecycle events",
    category: "trigger",
    color: "#15803d",
    icon: "CircleDollarSign",
    inputs: [],
    outputs: [{ id: "event-out", label: "Payment Event", type: "event" }],
    defaultConfig: { eventType: "payment_succeeded", provider: "runash-pay" },
  },
  {
    type: "payment.send_receipt",
    label: "Send Receipt",
    description: "Queue and send payment receipt to customer",
    category: "email",
    color: "#166534",
    icon: "ReceiptText",
    inputs: [{ id: "event-in", label: "Trigger", type: "event", required: true }],
    outputs: [{ id: "delivery-out", label: "Receipt", type: "event" }],
    defaultConfig: { templateId: "payment-receipt", channel: "email", queue: "automation" },
  },
  {
    type: "payment.notify_support",
    label: "Notify Support",
    description: "Alert support/on-call when payment issues occur",
    category: "email",
    color: "#7f1d1d",
    icon: "LifeBuoy",
    inputs: [{ id: "event-in", label: "Trigger", type: "event", required: true }],
    outputs: [{ id: "notification-out", label: "Support Alert", type: "event" }],
    defaultConfig: { severity: "high", destination: "support-queue", queue: "automation" },
  },
  {
    type: "payment.retry_reminder",
    label: "Retry Reminder",
    description: "Queue payment retry reminder for overdue or failed payments",
    category: "email",
    color: "#a16207",
    icon: "RotateCcw",
    inputs: [{ id: "event-in", label: "Trigger", type: "event", required: true }],
    outputs: [{ id: "reminder-out", label: "Reminder", type: "event" }],
    defaultConfig: { channel: "email", delayMinutes: 60, queue: "automation" },
  },
  {
    type: "payment.unlock_feature_entitlement",
    label: "Unlock Feature Entitlement",
    description: "Unlock paid entitlements after successful payment",
    category: "output",
    color: "#4338ca",
    icon: "KeyRound",
    inputs: [{ id: "event-in", label: "Trigger", type: "event", required: true }],
    outputs: [{ id: "entitlement-out", label: "Entitlement", type: "metadata" }],
    defaultConfig: { featureKey: "premium_access", mode: "grant" },
  },
  {
    type: "email.webhook_event_trigger",
    label: "Email Webhook Trigger",
    description: "Start workflow from an email webhook event",
    category: "trigger",
    color: "#0f766e",
    icon: "Webhook",
    inputs: [],
    outputs: [{ id: "event-out", label: "Webhook Event", type: "event" }],
    defaultConfig: { eventType: "delivered", provider: "resend" },
  },
  {
    type: "email.send_broadcast",
    label: "Send Broadcast",
    description: "Send campaign email to a contact segment",
    category: "email",
    color: "#1d4ed8",
    icon: "Send",
    inputs: [{ id: "event-in", label: "Trigger", type: "event", required: false }],
    outputs: [{ id: "delivery-out", label: "Delivery", type: "event" }],
    defaultConfig: { audienceId: "all-active", subject: "", templateId: "", provider: "resend" },
  },
  {
    type: "email.send_test",
    label: "Send Test Email",
    description: "Validate message rendering with a test recipient",
    category: "email",
    color: "#2563eb",
    icon: "MailCheck",
    inputs: [{ id: "event-in", label: "Trigger", type: "event", required: false }],
    outputs: [{ id: "delivery-out", label: "Delivery", type: "event" }],
    defaultConfig: { to: "", subject: "Test message", templateId: "", provider: "resend" },
  },
  {
    type: "email.import_contacts",
    label: "Import Contacts",
    description: "Import contacts from CSV/list source",
    category: "email",
    color: "#0f766e",
    icon: "UserPlus",
    inputs: [{ id: "event-in", label: "Trigger", type: "event", required: false }],
    outputs: [{ id: "contacts-out", label: "Contacts", type: "metadata" }],
    defaultConfig: { source: "csv", listName: "newsletter", dedupe: true },
  },
  {
    type: "email.handle_inbound_reply",
    label: "Handle Inbound Reply",
    description: "Classify inbound reply and route to agent queue",
    category: "email",
    color: "#0d9488",
    icon: "Reply",
    inputs: [{ id: "event-in", label: "Inbound Event", type: "event", required: true }],
    outputs: [
      { id: "triage-out", label: "Triage", type: "metadata" },
      { id: "agent-task-out", label: "Agent Task", type: "event" },
    ],
    defaultConfig: { sentimentModel: "default", confidenceThreshold: 0.75, assignToAgent: true },
  },
  {
    type: "camera-input",
    label: "Camera Input",
    description: "Capture live camera feed",
    category: "input",
    color: "#2563eb",
    icon: "Camera",
    inputs: [],
    outputs: [{ id: "video-out", label: "Video", type: "video" }],
    defaultConfig: { device: "default", resolution: "1080p", fps: 30 },
  },
  {
    type: "stream-key-input",
    label: "RTMP Input",
    description: "Ingest remote RTMP stream",
    category: "input",
    color: "#1d4ed8",
    icon: "Radio",
    inputs: [],
    outputs: [
      { id: "video-out", label: "Video", type: "video" },
      { id: "audio-out", label: "Audio", type: "audio" },
    ],
    defaultConfig: { source: "", reconnect: true },
  },
  {
    type: "video-trim",
    label: "Trim",
    description: "Trim timeline window",
    category: "video",
    color: "#7c3aed",
    icon: "Scissors",
    inputs: [{ id: "video-in", label: "Video", type: "video", required: true }],
    outputs: [{ id: "video-out", label: "Video", type: "video" }],
    defaultConfig: { start: 0, end: 30 },
  },
  {
    type: "video-overlay",
    label: "Overlay",
    description: "Add image/text overlays",
    category: "video",
    color: "#6d28d9",
    icon: "Layers",
    inputs: [{ id: "video-in", label: "Video", type: "video", required: true }],
    outputs: [{ id: "video-out", label: "Video", type: "video" }],
    defaultConfig: { title: "LIVE", position: "top-left", opacity: 0.8 },
  },
  {
    type: "ai-enhancer",
    label: "AI Enhancer",
    description: "Enhance video quality using AI",
    category: "ai",
    color: "#059669",
    icon: "Sparkles",
    inputs: [{ id: "video-in", label: "Video", type: "video", required: true }],
    outputs: [{ id: "video-out", label: "Enhanced Video", type: "video" }],
    defaultConfig: { denoise: true, sharpen: true, lowLightBoost: true },
  },
  {
    type: "ai-caption",
    label: "AI Caption",
    description: "Generate live captions",
    category: "ai",
    color: "#047857",
    icon: "Captions",
    inputs: [
      { id: "audio-in", label: "Audio", type: "audio", required: true },
      { id: "video-in", label: "Video", type: "video", required: false },
    ],
    outputs: [
      { id: "caption-out", label: "Captions", type: "text" },
      { id: "video-out", label: "Captioned Video", type: "video" },
    ],
    defaultConfig: { language: "en", style: "broadcast", profanityFilter: true },
  },
  {
    type: "multi-stream",
    label: "Multi Stream",
    description: "Broadcast to multiple platforms",
    category: "streaming",
    color: "#ea580c",
    icon: "Broadcast",
    inputs: [
      { id: "video-in", label: "Video", type: "video", required: true },
      { id: "audio-in", label: "Audio", type: "audio" },
    ],
    outputs: [{ id: "event-out", label: "Events", type: "event" }],
    defaultConfig: { youtube: true, twitch: true, instagram: false, bitrate: 6000 },
  },
  {
    type: "stream-analytics",
    label: "Analytics",
    description: "Track live stream KPIs",
    category: "streaming",
    color: "#c2410c",
    icon: "BarChart3",
    inputs: [{ id: "event-in", label: "Events", type: "event", required: true }],
    outputs: [{ id: "analytics-out", label: "Metrics", type: "analytics" }],
    defaultConfig: { intervalMs: 5000, alertDropThreshold: 30 },
  },
  {
    type: "record-output",
    label: "Recorder",
    description: "Store output stream",
    category: "output",
    color: "#be123c",
    icon: "Save",
    inputs: [{ id: "video-in", label: "Video", type: "video", required: true }],
    outputs: [],
    defaultConfig: { format: "mp4", path: "/recordings/live.mp4" },
  },
]

export function findNodeDefinition(type: string) {
  return WORKFLOW_NODE_DEFINITIONS.find((node) => node.type === type)
}

export function listNodeDefinitionsByCategory(category: WorkflowNodeDefinition["category"]) {
  return WORKFLOW_NODE_DEFINITIONS.filter((node) => node.category === category)
}
